### ISSUE TITLE
Inline code not visible in light mode

### ISSUE THREAD

**Issue by drewsilcock** [scttcper/gatsby-casper#68]
## Problem

The inline code has colour "white" as specified in the CSS for generic code blocks. When in light mode, the inline code is therefore not visible.

## Possible Fix

**`src/components/PostContent.tsx:588`**
```css
  :not(pre) > code[class*="language-"] {
    border-radius: 0.3em;
    background: var(--inlineCode-bg);
    color: var(--inlineCode-text);
    padding: 0.15em 0.2em 0.05em;
    white-space: normal;
  }
```

This produces the CSS selector: `.css-4cns0r-PostFullContent:not(pre) > code[class*="language-"]` - note the lack of space between the generated class and the `:not(pre)`. I presume emotion is thinking that the `:not(pre)` is a pseudo-selector like `:hover` or `:active` and deciding to combine the initial class with the `:not(pre)`. I've not used emotion before so I don't know how to fix this.

## Screenshot:

![image](https://user-images.githubusercontent.com/14921224/81081827-53582b00-8eea-11ea-817d-b0609d924457.png)
